TRUNK_TRANSACTION_TRINARY_OFFSET = 7290
TRUNK_TRANSACTION_TRINARY_SIZE = 243
BRANCH_TRANSACTION_TRINARY_OFFSET = 7533
BRANCH_TRANSACTION_TRINARY_SIZE = 243

MIN_WEIGHT_MAGNITUDE = 15

MAX_NUM_CONCURRENT_POW = 2

MAX_NUM_PENDING_TXS = 20
MIN_NUM_SECS_BETWEEN_ATTACHMENTS = 15 * 60
REATTACH_SURVEY_INTERVAL_IN_SECS = 60
MAX_NUM_MIN_OPEN_CONNECTION = 2

DEPTH = 4
