TRUNK_TRANSACTION_TRINARY_OFFSET = 7290
TRUNK_TRANSACTION_TRINARY_SIZE = 243
BRANCH_TRANSACTION_TRINARY_OFFSET = 7533
BRANCH_TRANSACTION_TRINARY_SIZE = 243

MIN_WEIGHT_MAGNITUDE = 15

MAX_NUM_CONNECTED_CLIENTS = 2